/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HotelManagement;

public class Hotel {
	String hotelName;
	int weekDayRate;
	int weekEndRate;
	int rating;
	int rateForRegularCustomer;
	int rewardWeekdayRates;
	int rewardWeekEndrates;
	public Hotel(String hotelName, int weekDayHotelRate, int weekEndHotelRate, int ratings,int rewardWeekdayRates,int rewardWeekEndrates) {
		this.hotelName = hotelName;
		this.weekDayRate = weekDayHotelRate;
		this.weekEndRate = weekEndHotelRate;
		this.rating = ratings;
		this.rewardWeekdayRates=rewardWeekdayRates;
		this.rewardWeekEndrates=rewardWeekEndrates;
	}

	public int getWeekDayRate() {
		return weekDayRate;
	}

	public void setWeekDayRate(int weekDayHotelRate) {
		this.weekDayRate = weekDayHotelRate;
	}

	public int getWeekEndRate() {
		return weekEndRate;
	}

	public void setWeekEndRate(int weekEndHotelRate) {
		this.weekEndRate = weekEndHotelRate;
	}

	public int getRating() {
		return rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	public String getHotelName() {
		return hotelName;
	}

	public int getRateForRegularCustomer() {
		return rateForRegularCustomer;
	}

	public void setHotelName(String hotelName) {
		this.hotelName = hotelName;
	}

	public void setRateForRegularCustomer(int rateForRegularCustomer) {
		this.rateForRegularCustomer = rateForRegularCustomer;
	}

	@Override
	public String toString() {
		return "hotelName=" + hotelName + ", rateForRegularCustomer=" + rateForRegularCustomer + "]";
	}
}
